app_root: /vagrant

# Nginxのインストール及び各種設定
nginx_install: true


# laravel
laravel_project: homestead

# www
www_doc_root: /vagrant/

# mysqlのインストール及び各種設定
mysql_install: true

mysql_db: homestead
mysql_user: root
mysql_password: 1234

# phpのインストール及び各種設定
php7_install: true
php7_xdebug_install: true # デバッガ
php7_composer_install: true # パッケージ管理ツール
php7_deployer_install: true # デプロイツール

# java1.8のインストール及び各種設定
java1_8_install: true

# nodejsのインストール及び各種設定
nodejs_install: true

# rubyのインストール及び各種設定
ruby_install: false


# golangのインストール及び各種設定
golang_install: true
