# php7のインストール

- name: install repository
  yum: name={{item}}
  with_items:
    - http://ftp.iij.ad.jp/pub/linux/fedora/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm



- name: setting repository.conf
  replace: dest=/etc/yum.repos.d/{{item}} regexp='enabled *= *1' replace='enabled=0'
  with_items:
    - epel.repo
    - remi.repo


- name: insatll php7
  yum: name={{item}} state=installed enablerepo=epel,remi-php70
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
    - php-intl
    - php-mcrypt
    - php-mbstring
    - php-mysqlnd
    - php-opcache
    - php-gd
    - php-pdo
    - php-pecl-imagick
    - php-pecl-imagick-devel
    - php-pecl-memcache
    - php-pecl-xdebug
    - php-pecl-zip
    - php-xml

- name: insatll composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar composer chdir=/usr/local/bin

- - name: copy xdebug config file
    template:
      backup=yes
      src=15-xdebug.ini
      dest=/etc/php.d/