# node.js + npm インストール

- name: install repository
  yum: name={{item}}
  with_items:
    - http://ftp.iij.ad.jp/pub/linux/fedora/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: setting repository.conf
  replace: dest=/etc/yum.repos.d/{{item}} regexp='enabled *= *1' replace='enabled=0'
  with_items:
    - epel.repo
    - remi.repo

- name: install node.js & npm
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - nodejs
    - npm

- name: install gulp
  npm: name=gulp global=yes

- name: install babel library
  shell: npm install --save babel-preset-es2015 babel-preset-react --no-bin-links

- name: install react library
  shell: npm install --save react react-dom babelify babel-preset-react

# yarnも入れます
- name: install yarn
  shell: npm install yarn