# Apache
- name: install Apache
  yum: name=httpd  state=installed
  notify: start httpd

- name: copy config file
  template:
    backup=yes
    src=httpd.conf
    dest=/etc/httpd/conf/
  notify: start httpd

- name: start httpd
  service: name=httpd state=started enabled=yes


